package TheOutput;

public class Output {
    public static void main(String[] args) {

    // To start with output in the java syntax ....
    /*some rule follow by java....
     * rule-1: every line terminated with simicolon....
     * rule-2: java is case sensitive language....
     * rule-3: inside the parantheses, we can do maths....
     * rule-4: write any collection of character then write 
     *         it inside the double quote to print as it is
     */

        //line terminate with semicolon....
        System.out.println(10);

        //inside the parantheses, can do maths....
        System.out.println(10+5);

        //use double quote as it print....
        System.out.println("welcome to java ");
        System.out.println("10+7");
        System.out.println("Hello OP Sharma");

        //java is case sensitive language...
        //System.out.Println("OP Sharma"); //because i am write println start from the capital letter ...
        
    }
}
